#默认使用配置
spring:
  profiles:
    active:
    - dev
    
#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: cn.mangot.wxcommon.entity
  mapperLocations: classpath:cn/mangot/wxcommon/mapping/*.xml
#==================== 日志配合·标准  ============================
logging:
  config: classpath:logback-boot.xml