spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/wxcommon?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
  #redis
  redis:
    password: 123456
    database: 0
    port: 6379
    jedis:
      pool:
         max-idle: 8
         min-idle: 0
         max-active: 8
         max-wait: -1
    host: localhost
    timeout: 0
server:
  port: 9876